### PR TITLE
add light/dark mode and support utterances

### PR DESCRIPTION
**Pull request by jiwhunkim**
support utterances
```
[params]
UtterancesRepo = "reponame"
UtterancesIssueTerm = "pathname"
```

add light/dark theme

### CODE REVIEW

**Comment by lovesegfault** [comment]
I'm testing this, cc. @funkydan2

**Comment by lovesegfault** [comment]
Utterances support looks good, how am I supposed to force dark theme?

**Comment by lovesegfault** [comment]
Alright, by manually fiddling with the CSS I've got this to work, here's my feedback:

1. Uterrances comments look weird in dark mode
2. The dark mode is _DARK_ I wish softer colors than "pitch black" were used. Maybe a dim mode?
3. It needs a way to be forced at config-time, as well as perhaps switched by the user (a button, perhaps?)

**Comment by jiwhunkim** [comment]
Ok I try apply feedback
Thank you

**Comment by jiwhunkim** [comment]
1. 
for example
```
[params]
    UtterancesRepo = "reponame"
    UtterancesIssueTerm = "pathname"
    UtterancesLightTheme = "github-light"
    UtterancesDarkTheme = "github-dark"
```
you choose Utterances light/dark theme

2.
apply style-dark.css
background: #2A2829;
I find way css variable like scss on hexo

3. I find way how to toggle
prefers-color-scheme: dark

**Comment by lovesegfault** [comment]
@jiwhunkim Looks good!

Tested on my website and the softer background is nice and utterances theme picking works as well.

Still unsure how to force-enable dark mode, but other than that all looks good!

**Comment by funkydan2** [comment]
Cool - so with this PR, the developer can't 'force' light or dark mode, but it will match the viewer's system settings. I like! Thanks @jiwhunkim  and @lovesegfault

**Pull request merged**
