### PR TITLE
Added tags to the main nav toolbar

### LINKED ISSUE #13: add support fot tags and categories
This would be a very positive usability enhancement as it makes finding related content way easier

### PR DESCRIPTION
**Pull request by alfredocambera**
Fixes #13

### CODE REVIEW

**Comment by funkydan2** [comment]
I agree that this works, and it could be included in the example site.

However, as your code example shows, this is a built-in Hugo feature. [You can link to a taxonomy the way you have](https://gohugo.io/content-management/taxonomies#default-destinations). I'm not sure if it needs to be shown in the example site's config.

**Comment by alfredocambera** [comment]
As a newbie Hugo user, I thought the theme didn't have support for tags. Probably some other users will have gotten the same impression.

It is more attractive and intuitive to have all the features enabled so you can comment out those you don't need.

Also, I think than adding a screenshot of the template on the `README.md` would help with the adoption of the theme.

What do you think?

**Comment by alfredocambera** [comment]
I didn't understand your comment about linking to a taxonimy. Could you please elaborate?

**Comment by funkydan2** [comment]
I've had a go of (1) putting a screenshot and (2) putting [information about tags and categories](https://github.com/funkydan2/hugo-kiera#categories--tags) in the README file. Do you think that will help new users, rather than adding complexity to the example site?

Taxonomies are different ways of organising data (pages) in Hugo built sites. The simplest way is through tags or categories...but Hugo is very flexible, so you can have other taxonomies, like author or mood...whatever you want. And for whatever taxonomy you define, a *list* page is built so you can browse all the data available (like what you've discovered with tags). I'm not sure where it's mentioned in the Hugo documentation - but maybe [start here](https://gohugo.io/templates/taxonomy-templates/).

**Comment by alfredocambera** [comment]
I think the default config if very simple, it only has `Posts` and `About`. Most of the templates have this feature (enabled by default or commented out).

If you think that would add too much complexity here is my suggestion:

* Improve `README.me` to mention that tags and categories are a feature disabled by default but available.
* Add a commented out section for `tags` and `categories` on the `config.toml`.

We could also add a `full-config.toml` with all the features configuration parameters uncommented. It wouldn't be the default file but we could mention its existence on the `README.md`. 


Regarding the screenshot, I think it is necessary to have one on the `README.md` as:

* Most ([1](https://github.com/gcushen/hugo-academic), [2](https://github.com/olOwOlo/hugo-theme-even)) the themes have this on their github repositories.
* If looking for a theme you expect at least a picture of how the theme looks like.

**Comment by funkydan2** [comment]
Has this issue been solved by PR #16 and PR #18 ?

**Comment by alfredocambera** [comment]
No, the code is here https://github.com/funkydan2/hugo-kiera/pull/15/commits/e4025ce8dd0dba59119342cc34034764a82beea6#diff-991d2a2fe208cdee83955ad6e9a323a7R30-R36.

Shall I add it commented to the config.toml? or we can leave it as the referred fragment of code

**Comment by funkydan2** [comment]
A commented-out example would be fine by me. Since it's not a 'theme feature' I don't see the need of having it specifically shown in the example site.

**Comment by alfredocambera** [comment]
I'll send a new one. Meesed up the rebase

**Pull request closed without merging**
