### PR TITLE
Align right post nav link to the right

### PR DESCRIPTION
**Pull request by paulwellnerbou**

### CODE REVIEW

**Comment by funkydan2** [comment]
Thanks for the PR. Can you help me understand what this change does?

**Comment by funkydan2** [comment]
...actually, I understand what it does now. It fixes the layout for the first/last post, where there's not both 'next' and 'previous'  navigation available, and so `justify-content: space-between;` doesn't quite work.

**Comment by paulwellnerbou** [comment]
Sure. It aligns the link to the previous (older) post to the right, even if it has more than one line.

Before:
Screenshot from 2021-11-13 10-13-14

After:
Screenshot from 2021-11-13 10-17-14

In addition to that, it aligns it to the right even if there is no next (more recent) post (second commit):

Before:
Screenshot from 2021-11-13 10-15-59

After:
Screenshot from 2021-11-13 10-16-38

**Comment by paulwellnerbou** [comment]
Thanks!

**Pull request merged**
